// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/app/context/UserContext"; 
import { QueryProvider } from "@/components/provider/QueryProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hymns Village",
  description: "Generated by Christee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <QueryProvider>
        <UserProvider>
          {children}
        </UserProvider>
        </QueryProvider>
        
      </body>
    </html>
  );
}
