import type { Metadata } from "next"
import { Geist, Geist_Mono } from 'next/font/google';
import Navbar from "@/components/Navbar";
import AdvertisementSection from "@/components/Advert";
import Footer from "@/components/footer";



const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Hymns village",
  description: "Generated by Christee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
         <AdvertisementSection />
        <Footer />
      </body>
    </html>
  );
}
