import type { Metadata } from "next"
import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Hymns village",
  description: "Generated by Christee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <> 
        <Navbar />
        {children}
        <Footer />
      </>
  );
}
